# Version 2.0 - Updated
echo "==============================="
echo "   SYSTEM INFORMATION REPORT"
echo "==============================="
echo "Date & Time : $(date)"
echo "Hostname    : $(hostname)"
echo "OS          : $(lsb_release -d | cut -f2)"
echo "Kernel      : $(uname -r)"
echo "Uptime      : $(uptime -p)"
echo "CPU         : $(nproc) cores"
echo "RAM Total   : $(free -h | awk '/Mem/{print $2}')"
echo "RAM Used    : $(free -h | awk '/Mem/{print $3}')"
echo "Disk Usage  : $(df -h / | awk 'NR==2{print $5}')"
echo "IP Address  : $(hostname -I | awk '{print $1}')"
echo "==============================="
